# Generated by Django 3.2 on 2024-04-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_location', models.CharField(blank=True, max_length=100, null=True)),
                ('review', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
